### ISSUE TITLE
Settings menu crashes as soon as I click on an app

### ISSUE THREAD

**Issue by mlangc** [jclehner/AppOpsXposed#8]
Unfortunately the settings menu crashes as soon as I click on an app in the list. I tried both failsave and compatibility mode, but that didn't help. You can find my report file [here](https://spideroak.com/share/NRXWY5LLOVVWC43TOVZQ/AppOpsXposed/home/mlangc/Public/attachments/AppOpsXposed/report_c1d5419bf53b_20150103091044.txt). Please note that I don't think that the SecurityExceptions you find there are related to my original problem, as they only show up in "Compatibility Mode" (that would be another issue though ;-)).

Thank you very much,
Matthias

**Comment by jclehner** [comment]
Try one of the following (ideally both):

* Disable "Layout fix" in the module's settings (accessible via Xposed Installer) and try again (without compatibility mode).

* In case you didn't reboot after enabling "Compatibility mode", do that and try again (`SecurityException`s should go away).

**Comment by mlangc** [comment]
Hmm, I did't know that you have to reboot after changing a setting; Disabling "Layout fix" and rebooting did the trick - thanks!

**Comment by jclehner** [comment]
This has to do with the particularities of Xposed; almost all settings in AppOpsXposed require a reboot. The reported bug was fixed in 6066effd and will be included in the next release!
