### ISSUE TITLE
In AppOpsDetail,label "location"  show as "coarse location"

### ISSUE THREAD

**Issue by darkgentry** [jclehner/AppOpsXposed#9]
From cm's array.xml,these ops should show as "location".
 
    <string-array name="app_ops_labels">
        <item>Location</item>   .....app_ops_summaries_coarse location
        <item>Location</item>   .....app_ops_summaries_fine location
        <item>Location</item>   .....app_ops_summaries_GPS
        ....................................

also, <item>Receive SMS/MMS</item>   .....app_ops_summaries_receive SMS
        <item>Receive SMS/MMS</item>   .....app_ops_summaries_receive emergency SMS
        <item>Receive SMS/MMS</item>   .....app_ops_summaries_receive MMS
        <item>Receive SMS/MMS</item>   .....app_ops_summaries_receive WAP push

**Comment by jclehner** [comment]
I've fixed this already; will release tomorrow!
